#!/bin/bash

cite()
{
  if [ ${e:0:1} == G ]; then
    printf '%s~\\cite{ligocat}' $e
  else
    printf '\\citegcn{%s}' $e
  fi
}

mt02ndligo()
{
  e=$1
  mass=$2
  t=$3

  ligopass2/ligopass2.sh ligoresults-$e/20*fardet-t02.hadded.root | \
    grep snprob$mass | awk '{print $2, $3}' > a$e &
  ligopass2/ligopass2.sh ligoresults-$e/20*neardet-ligo.hadded.root | \
    grep snprob$mass | awk '{print $3}' > b$e &

  wait

  paste a$e b$e > comb$e

  if [ $mass == 27 ]; then
    printf '%24s & %11s & Untriggered & %5s ' \
      $(cite $e) $t \
      $(ligopass2/find90 $e $mass < comb$e | awk '{print $13}')
  else
    printf '& %5s \\\\\n' \
      $(ligopass2/find90 $e $mass < comb$e | awk '{print $13}')
  fi
}

mt02ndligo $1 27  $2
mt02ndligo $1 9.6 $2
